on:
  push:
    branches: ['2024']
name: ðŸš€ Deploy Site w/FTP
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'npm'
      - name: ðŸ”¨ Build Project
        run: |
          npm install
          npm run build
      - name: ðŸš¢ Deploy Static Site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          # protocol: ftps
          port: ${{ secrets.ftp_port }}
          local-dir: './build/'
          server-dir: '2024.mcbios.com/'
      - name: ðŸ›¸ Post-Deploy ðŸ‘½
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          dangerous-clean-slate: false
          port: ${{ secrets.ftp_port }}
          local-dir: './post-deploy/'
          server-dir: '2024.mcbios.com/'
