on:
  pull_request:
    branches: ['2024']
name: ğŸ— Build site
jobs:
  build-site:
    name: ğŸ¥´ Build ğŸ”§
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'npm'
      - name: ğŸ”¨ Build Project
        run: |
          npm install
          npm run build
      # - name: ğŸ›¸ Enrich Package ğŸ‘½
      #   run: cp ./post-deploy/.htaccess ./build/
      # - name: ğŸš¢ Deploy Static Site (Dryrun)
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.ftp_server }}
      #     username: ${{ secrets.ftp_user }}
      #     password: ${{ secrets.ftp_password }}
      #     # protocol: ftps
      #     port: ${{ secrets.ftp_port }}
      #     local-dir: './build/'
      #     server-dir: '2024.mcbios.com/'
      #     dry-run: true
